### ISSUE TITLE
Add Documentation for Actions

### ISSUE THREAD

**Issue by maennchen** [victorgarciaesgi/Vuex-typed-modules#1]
Describe how actions are defined and how an action calls mutations (typed).

I've tried to find out myself and open a Documentation PR, but neither of the found solutions were working as expected.

1. Use `context.commit` - no types present for the mutation
2. Use `mutation(context.state)` - vuex complains that a mutation is called outside of a commit

**Comment by victorgarciaesgi** [comment]
Hi @maennchen , thanks for the feedback!
I've updated the docs with actions exemples.
along with some bug fixes on 1.0.2
