### ISSUE TITLE
calling mutation inside action in the VuexModule

### ISSUE THREAD

**Issue by paulvanbladel** [victorgarciaesgi/Vuex-typed-modules#4]
In your example you are self referencing testModule inside the action.

```
const actions = {
  async addCountAsync(context, count: number): Promise<void> {
    await myAsyncFunction(count);
  // Calling mutation
    testModule.mutations.addCount(count);
  }
},
```

I think that **context** parameter should be used here, no?
In a regular store,  the context parameter is used for calling the mutation inside the action.
See https://vuex.vuejs.org/guide/actions.html
so, context.commit is used there, but i guess you want to do something that leverages typings...

I adapted the action on the sample I sent you earlier to:
```
,
  actions: {
    increment (context, count) {
      context.commit('addCount', count)
    }
  }
```
This works, but of course there is no typing.
Any suggestion from your side?
Cheers
paul.

**Comment by victorgarciaesgi** [comment]
It was impossible to infer action function types and at the same time extends Context type, it was either one.
I would love to have context typed but i didn't manage to do it for now... :(
That's why the workaround is to call the module instead

**Comment by paulvanbladel** [comment]
No worries. Thanks.
